Repository CheoCharm/MapZ-Android, pull requests merged in 2022-08, with the labels that each got.

#29 #27 fix: UI가 화면 비율에 따라 상하로 치우치는 문제 해결
  presentation/src/main/res/layout/fragment_picture.xml
  presentation/src/main/res/values/dimens.xml
Labels: 🐞bug

#41 [develop] 위치 확인하기 화면 구현
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/cheocharm/presentation/common/ext.kt
  presentation/src/main/java/com/cheocharm/presentation/model/Picture.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/search/SearchFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/GroupsFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/LocationFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/PictureFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/PictureViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/PicturesAdapter.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/WriteFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/util/GeocodeUtil.kt
  presentation/src/main/res/drawable/bg_radius_10dp.xml
  presentation/src/main/res/drawable/ic_confirm.xml
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/drawable/ic_marker.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_groups.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_location.xml
  presentation/src/main/res/layout/fragment_my_page.xml
  presentation/src/main/res/layout/fragment_picture.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/fragment_write.xml
  presentation/src/main/res/layout/item_location_picture.xml
  presentation/src/main/res/menu/menu_location.xml
  presentation/src/main/res/navigation/nav_write.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: 🎨design, 🛩develop, 🖥feature

#42 [develop] 구글 로그인, 회원가입 구현
  data/src/main/java/com/cheocharm/data/error/ErrorData.kt
  data/src/main/java/com/cheocharm/data/error/ErrorMapper.kt
  data/src/main/java/com/cheocharm/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/cheocharm/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/cheocharm/data/source/AuthLocalDataSource.kt
  data/src/main/java/com/cheocharm/data/source/LoginRemoteDataSource.kt
  domain/src/main/java/com/cheocharm/domain/model/Error.kt
  domain/src/main/java/com/cheocharm/domain/model/GoogleSignUpRequest.kt
  domain/src/main/java/com/cheocharm/domain/repository/AuthRepository.kt
  domain/src/main/java/com/cheocharm/domain/repository/LoginRepository.kt
  domain/src/main/java/com/cheocharm/domain/usecase/RequestGoogleSignInUseCase.kt
  domain/src/main/java/com/cheocharm/domain/usecase/RequestGoogleSignUpUseCase.kt
  domain/src/main/java/com/cheocharm/domain/usecase/RequestSignOutUseCase.kt
  domain/src/main/java/com/cheocharm/domain/usecase/SaveSignInTypeUseCase.kt
  local/src/main/java/com/cheocharm/local/source/AuthLocalDataSourceImpl.kt
  presentation/src/main/java/com/cheocharm/presentation/common/Constants.kt
  presentation/src/main/java/com/cheocharm/presentation/model/SignType.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/login/SignInFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/login/SignInViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/login/SignUpAgreeFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/login/SignUpProfileFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/login/SignViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/mypage/MyPageFragment.kt
  remote/src/main/java/com/cheocharm/remote/api/LoginApi.kt
  remote/src/main/java/com/cheocharm/remote/mapper/SignMapper.kt
  remote/src/main/java/com/cheocharm/remote/model/GoogleSignInResponse.kt
  remote/src/main/java/com/cheocharm/remote/model/GoogleSignUpResponse.kt
  remote/src/main/java/com/cheocharm/remote/model/request/GoogleSignUpDto.kt
  remote/src/main/java/com/cheocharm/remote/source/LoginRemoteDataSourceImpl.kt
Labels: 🛩develop, 🖥feature
