Repository CheoCharm/MapZ-Android, pull requests merged in 2022-06, with the labels that each got.

#10 [develop] local 모듈 build.gradle에 test 코드 관련 dependencies 추가
  local/build.gradle
Labels: 🐞bug

#11 [develop] github actions 설정을 위해 android.yml 추가
  .github/workflows/android.yml
Labels: 🐞bug

#8 [develop] github actions 설정을 위해 android.yml 추가
  .github/workflows/android.yml
Labels: 🛩develop, 🖥feature

#14 [develop] bottom nav 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  base/src/main/java/com/cheocharm/base/BaseActivity.kt
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/cheocharm/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/mypage/MyPageFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/search/SearchFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/search/SearchViewModel.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/WriteFragment.kt
  presentation/src/main/java/com/cheocharm/presentation/ui/write/WriteViewModel.kt
  presentation/src/main/res/drawable/ic_bottom_home.xml
  presentation/src/main/res/drawable/ic_bottom_my_page.xml
  presentation/src/main/res/drawable/ic_bottom_search.xml
  presentation/src/main/res/drawable/ic_bottom_write.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_my_page.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/fragment_write.xml
  presentation/src/main/res/menu/menu_main.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 🖥feature

#15 [develop] 홈 화면에 지도 노출
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/cheocharm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/res/layout/fragment_home.xml
Labels: 🛩develop, 🖥feature

#16 [develop] 홈 화면에 지도 노출
  app/build.gradle
  presentation/build.gradle
Labels: 🛩develop, 🖥feature
